### ISSUE TITLE
New suit2p naming convention

### ISSUE THREAD

**Issue by Milamber64** [cawarwick/Grouped-Z-projector#8]
The newest version of suite2p v0.14.3 uses a different naming convention for output files compared to the previous versions. This results in an error when the suit2p processor tries to open the stabilized data files. Changing the naming convention in the for loop on line 37, line 40, line 265, and 268 is required. I have included a copy of the revised code that takes into account this name change for the suite2p output. 

Line 37:
filename = "file00000_chan0.tif"; //increased the number of zeros from "file000_chan0.tif" to "file00000_chan0.tif"

Line 40:
filename = "file00" + frame + "_chan0.tif"; //changed "file" to "file00"

Line 265:
file="file00000_chan1.tif"; //same as above changed "file000_chan1.tif" to "file00000_chan1.tif"

Line 268:
file = "file00" + frame + "_chan1.tif"; //changed "file" to "file00" to accommodate naming of files from suite2p

**Comment by cawarwick** [comment]
Issue has been fixed with latest comit.
